### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by BTopbas** [diyhue/DiyLeaf#1]
This is a working project? Any real photo or video?

**Comment by mariusmotea** [comment]
Hi,

This is working but still require improvements on the case side. I don't have a light difusser yet and this is a big minus.

**Comment by BTopbas** [comment]
Software is compatible with the original Nanoleaf app? The only minus is a diffuser? And the part list is very specific. We cannot use more accessible items like Arduino pro mini etc? And another thing is PCB. Custom PCB is not easily accessed too. Led parts, maybe we can use ws2815 144led/m led strip 6 led every corner? and some 3d printed case with cable connection paths?

**Comment by mariusmotea** [comment]
It is intended to work only with the hue emulator, so you can use hue apps to control these panels (including Hue Sync). I use Attiny85 because is small and cheap. I start with WS2812 which is 5050 format but i notice the case was very thick, so i found the original panels use 3535 leds and ws2812 are available also in this format. You can use arduino, WS281x, but the PCB's and the 3D case from here will not work. Is easy to give it a try if you have one ESP8266 board, one level shifter for i2c bus, arduino boards and WS281x strips

**Comment by BTopbas** [comment]
Thanks for the reply! If I will use esp01's every panel and so every panel has different IP and can control separately. is have any minus? (I want to use 9 or more panels.) Or only one IP with data connection between panels And change lights count so split separate panels? Which one is better to do you think?

**Comment by mariusmotea** [comment]
If you want to have wifi to every panel and to control it directly from the bridge is very simple, use esp8266 board with generic sw2812 sketch, but this project want to have one master board with esp8266 and controll all other panels using i2c bus.

**Comment by nasimshah05** [comment]
i have connect with router but can't connect the esp with emulator.please help

**Comment by mariusmotea** [comment]
Open new issue and show logs during light search.
